### ISSUE TITLE
Infinite Cigarettes

### ISSUE THREAD

**Issue by GeminusCity** [GeminusCity/Geminus-City#1]
**Brief description of the issue**
Upon exhaustion of a cigarette, a burnt stub is dropped, but the 'almost dead' cigarette is not removed from your mouth.

**What you expected to happen**
Upon a cigarette burning out for it to be changed to a stub in my mouth, or deleted from my mouth and a stub to be dropped on the ground.

**What actually happened**
A permanently 'almost burnt out' cigarette remains in my mouth when it should be exhausted (which I can treat as a normal item, albeit one that burns indefinitely) while a burnt out stub is also dropped at my feet. The permanent cigarette does not produce nicotine benefits, notably.

**Steps to reproduce**
1;) smoke a cigarette
2:) wait
3:) observe that it never goes out, just stops at the last stage, and a burnt out stub is dropped at your feet.

**Comment by GeminusCity** [comment]
/code/game/objects/items/weapons/cigs_lighters.dm is the pertinent file. Quick glance LOOKS like it's correct.

**Comment by vekotov** [comment]
After testing I can say what this is because of runtime in transfer_fingerprints_to(butt) (cigs_lighters.dm:192)
Futher investigation required.
