### ISSUE TITLE
Refined Materials Holder being cocky.

### ISSUE THREAD

**Issue by HerbertFalsevor** [GeminusCity/Geminus-City#5]
#### Brief description of the issue
Refined materials holder only takes in some materials. Not all. For example, it does not take in plasteel, steel, any sort of ingots, uranium sheets and quartz. Yet it does take in glass, reinforced glass and wood.
#### What you expected to happen
I expected it to take in all refined materials that could be mined.
#### What actually happened
See brief description
#### Steps to reproduce
1.  Try to put iron ingot or other material in the Refined Materials Holder.
2.  Get disappointed.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
Penis

**Comment by GeminusCity** [comment]
There are two other constructable objects in the game: metals holder and gemstone cabinet. They each hold different materials, and altogether contain all the minables.
