### ISSUE TITLE
Robotic feet don't work when put on amputees

### ISSUE THREAD

**Issue by at996** [GeminusCity/Geminus-City#9]
#### Brief description of the issue
Robotic feet apparently don't work on humans (tried it out with Jeremy Thompson and he kept falling down even after we put the robotic feet on)

#### What you expected to happen
A nice and clean successful surgery finished
#### What actually happened
Robotic feet refused to work and Thompson kept collapsing as the result.

#### Steps to reproduce
Put a robotic feet in a person with one less feet to see the results.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
 - master - 2021-06-30

**Comment by vekotov** [comment]
Are Jeremy Thompson has cyberware for robotic feet?
I mean it needed for functioning of prostesics.
![image](https://user-images.githubusercontent.com/38394905/124369802-09a7d380-dc9a-11eb-8208-70a41bb7d7e7.png)

**Comment by at996** [comment]
> Are Jeremy Thompson has neural framework implant?
> I mean it needed for functioning of prostesics.
> ![image](https://user-images.githubusercontent.com/38394905/124369802-09a7d380-dc9a-11eb-8208-70a41bb7d7e7.png)

uh no he didn't have the implant, but DAMN that sucks if thats the case, should maybe make that not required for replacement...
